# Generated by Django 3.2.5 on 2021-08-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_colis'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
