# Generated by Django 3.2.5 on 2021-08-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_auto_20210802_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.marque')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.category'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.marque'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.modele'),
        ),
    ]
