# Generated by Django 3.2.5 on 2021-08-02 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_auto_20210802_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='annee',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='estALouer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicule',
            name='estAVendre',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage',
            field=models.PositiveSmallIntegerField(default=18001),
            preserve_default=False,
        ),
    ]
