# Generated by Django 3.2.5 on 2021-08-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_commande_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitcommande',
            old_name='vehicule',
            new_name='associateVvehicule',
        ),
    ]
