# Generated by Django 3.2.5 on 2021-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_rename_vehicule_produitcommande_associatevvehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='lieu_livraison',
            field=models.CharField(default='not defined', max_length=100),
        ),
    ]
