# Generated by Django 3.2.5 on 2021-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_commande_lieu_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
