# Generated by Django 3.2.5 on 2021-08-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210806_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeinstance',
            name='already_used',
            field=models.BooleanField(default=False),
        ),
    ]
